In [1]:
import numpy as np
# Step 1: Generate a 3x4 random matrix
matrix_3x4 = np.random.randint(1, 21, size=(3, 4)) # Adjust range as needed
A = matrix_3x4[:, :3] # Coefficient matrix (first 3 columns)
b = matrix_3x4[:, 3] # Right-hand side vector (last column)
print("Generated 3x4 Matrix:")
print(matrix_3x4)
print("\nCoefficient Matrix (A):")
print(A)
print("\nRight-hand Side Vector (b):")
print(b)

Generated 3x4 Matrix:
[[ 4 14 11 17]
 [11 16  2 15]
 [13 16  8  4]]

Coefficient Matrix (A):
[[ 4 14 11]
 [11 16  2]
 [13 16  8]]

Right-hand Side Vector (b):
[17 15  4]


In [2]:
# Solve using Matrix Inverse Method
try:
    A_inv = np.linalg.inv(A)  # Compute A^-1
    x_manual = np.dot(A_inv, b)  # x = A^-1 * b
    print("\nSolution using Matrix Inverse Method:")
    print(x_manual)
except np.linalg.LinAlgError:
    print("\nMatrix A is singular and cannot be inverted.")

# Solve using Gaussian Elimination
x_gaussian = np.linalg.solve(A, b)  # Direct Gaussian elimination
print("\nSolution using Gaussian Elimination (NumPy):")
print(x_gaussian)

# Verify the solution
b_check = np.dot(A, x_gaussian)  # Recompute b using A and the computed x
print("\nVerification (Ax = b):")
print(b_check)


Solution using Matrix Inverse Method:
[-2.3923445   2.71172249 -1.03588517]

Solution using Gaussian Elimination (NumPy):
[-2.3923445   2.71172249 -1.03588517]

Verification (Ax = b):
[17. 15.  4.]
